### PR TITLE
WIP V3 Bolt PR

### PR DESCRIPTION
**Pull request by Raistlfiren**
Here is an update of this extension working with V3 of Bolt. I would like to refactor the TWIG extension before releasing it though.

Cheers!

### CODE REVIEW

**Comment by jadwigo** [comment]
Thanks,

I opened up a branch for the bolt 3.x extension for this ... I have to find some time to test everything though.

**Comment by Raistlfiren** [comment]
It should be working on V3. I won't be able to do anything more with this extension at the current time.

**Comment by jadwigo** [comment]
Well, finally got around to test it - and it works for me :)
@Raistlfiren Thanks for the hard work!

**Pull request merged**
